app:
  api-prefix: /api
  security:
    public-endpoints:
      - .*/auth/login
      - .*/auth/logout
      - .*/auth/refresh-token
      - .*/auth/request-new-token
      - .*/auth/register
      - .*/auth/verify-mfa-login
      - .*/auth/verify-register
      - .*/auth/passkey/login/start
      - .*/auth/passkey/login/finish
      - .*/auth/ott/login/start
      - .*/auth/ott/login/finish
      - .*/s/g
      - .*/account/reset-password
      - .*/account/confirm-reset-password
      - .*/account/confirm-mfa-change-password
      - .*/auth/login

  auth-service:
    url: http://localhost:8081
spring:
  banner:
    location: tiger-banner.txt
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: sso_service
          uri: ${app.auth-service.url}
          predicates:
          - Path=${app.api-prefix}/oauth/**
          filters:
          # 2 for prefix path /api
          - StripPrefix=1
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 500
              redis-rate-limiter.burstCapacity: 1000
              redis-rate-limiter.requestedTokens: 1
              key-resolver: "#{@ipKeyResolver}"
        - id: customer_service
          uri: http://localhost:8082/customer
          predicates:
          # require header contain
          # - Header=x-request-id
          - Path=${app.api-prefix}/customer/**
          filters:
          # 2 for prefix path /api
          - StripPrefix=1
        - id: notification_adapter
          uri: http://localhost:8084/notification-adapter
          predicates:
            - Path=${app.api-prefix}/notification-adapter/**
          filters:
            # 2 for prefix path /api
            - StripPrefix=1
        - id: notification_service
          uri: http://localhost:8085/notification-service
          predicates:
            - Path=${app.api-prefix}/notification-service/**
          filters:
            # 2 for prefix path /api
            - StripPrefix=1
        - id: document_service
          uri: http://localhost:8094/document
          predicates:
            - Path=${app.api-prefix}/document/**
          filters:
            # 2 for prefix path /api
            - StripPrefix=1
        - id: order_service
          uri: http://localhost:8095/order
          predicates:
            - Path=${app.api-prefix}/order/**
          filters:
            # 2 for prefix path /api
            - StripPrefix=1
        - id: product_service
          uri: http://localhost:8096/product
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            # 2 for prefix path /api
            - StripPrefix=1
        - id: shipment_service
          uri: http://localhost:8097/shipment
          predicates:
            - Path=${app.api-prefix}/shipment/**
          filters:
            # 2 for prefix path /api
            - StripPrefix=1
        - id: payment_service
          uri: http://localhost:8098/payment
          predicates:
            - Path=${app.api-prefix}/payment/**
          filters:
            # 2 for prefix path /api
            - StripPrefix=1
        - id: drool_service
          uri: http://localhost:8099/drool
          predicates:
            - Path=${app.api-prefix}/drool/**
          filters:
            # 2 for prefix path /api
            - StripPrefix=1

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE